# Generated by Django 2.0.5 on 2018-05-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_shop_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('childcid', models.CharField(max_length=10)),
                ('productid', models.CharField(max_length=10)),
                ('longname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('marketprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_brand_product',
            },
        ),
        migrations.CreateModel(
            name='MainShowBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('categoryid', models.CharField(max_length=10)),
                ('brandname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_brand',
            },
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MainShowBrand'),
        ),
    ]
