# Generated by Django 2.0.5 on 2018-05-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_fondtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fondtype',
            old_name='childtypename',
            new_name='childtypenames',
        ),
    ]
