# Generated by Django 2.0.5 on 2018-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20180525_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payType',
            field=models.IntegerField(choices=[(0, '余款'), (1, '支付宝'), (2, '微信')], default=0),
        ),
    ]
